[package]
name = "rust-rps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.2.1"
bytemuck = "1.13.1"
libloading = "0.8.0"
pollster = "0.3.0"
rspirv-reflect = "0.7.0"
structopt = "0.3.26"
wgpu = { version = "0.16.0", features = ["spirv"] }
winit = "0.28.4"

[build-dependencies]
bindgen = "0.65.1"
cmake = "0.1.50"
